import type { Metadata } from "next";
import { Kaisei_Opti } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/context/AuthContext'; 

const kaiseiOpti = Kaisei_Opti({
  weight: ["400", "700"], // Kaisei Opti で利用可能なウェイトを指定。Google Fontsで確認
  subsets: ["latin"],
  display: "swap",
  variable: "--font-kaisei-opti", // CSS変数名
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kaiseiOpti.variable} antialiased`}
      ><AuthProvider>
        <audio id="bgm-A" src="/5.mp3" loop></audio>
<audio id="bgm-B" src="/mei.mp3" loop></audio>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
